name=Ascon128
version=1.0.0
author=Hauke D <haukex@zero-g.net>
maintainer=Hauke D <haukex@zero-g.net>
sentence=Ascon-128 and Utility Functions for Arduino
paragraph=This library includes implementations of Ascon-128 (by Rhys Weatherley), hexadecimal en-/decoding, and Z85 encoding utility functions.
category=Communication
url=https://github.com/haukex/arduino-ascon128
architectures=*
